"""Write static/_redirects so links to the old site's pages and files still work.

    python tools/redirects.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

PAGES = {
    "/index.php": "/",
    "/Home.php": "/",
    "/FAQ.php": "/faq/",
    "/Copied-Home.php": "/workshop/",
    "/Qualifier.php": "/qualifier/",
    "/Contact-Us.php": "/contact/",
    "/Photos-2015.php": "/photos/2015/",
    "/2015-Match-results.php": "/results/2015/",
}
# The old site named each year's results page after the previous year.
PAGES.update({f"/Copied-{y - 1}-Match-results.php": f"/results/{y}/" for y in range(2016, 2027)})


def main():
    legacy = json.loads((ROOT / "tools" / "legacy_map.json").read_text())
    lines = ["# Generated by tools/redirects.py: old site URLs -> new pages.", ""]
    lines += [f"{old}  {new}  301" for old, new in PAGES.items()]
    lines += ["", "# Old /documents and /images paths -> case-safe copies."]
    lines += [f"{old}  {new}  301" for old, new in sorted(legacy.items())]
    (ROOT / "static" / "_redirects").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(len(PAGES) + len(legacy), "redirects")


if __name__ == "__main__":
    main()
